#!/usr/bin/env bash

entries=(
    "Performance"
    "Balanced"
    "Power Saver"
)

selection=$(printf '%s\n' "${entries[@]}" | rofi -dmenu -p '' -i -theme ~/.config/rofi/option-menu.rasi)

case "$selection" in
    "Performance") powerprofilesctl set performance ;;
    "Balanced")    powerprofilesctl set balanced ;;
    "Power Saver") powerprofilesctl set power-saver ;;
esac
