#!/usr/bin/env bash

# Configuration for xidlehook, ran by i3
# Copied and modified from https://gitlab.com/jD91mZM2/xidlehook

# Only exported variables can be used within the timer's command
# export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Relies on brightnessctl (for its accurate backlight control)

if command -v xidlehook && command -v brightnessctl
then
    # Run xidlehook
    # At 5 minute - turn screen off
    # (`systemctl suspend` is not used due to its impact)
    xidlehook \
        --not-when-fullscreen --not-when-audio \
        --timer 300 \
        "brightnessctl --save set 0 >/dev/null" \
        "brightnessctl --restore >/dev/null"
else
    # Run xautolock if xidlehook not installed
    xautolock -time 5 -locker "xset dpms force off" -detectsleep
fi
