#!/usr/bin/env bash

# Configuration for xidlehook, ran by i3
# Copied and modified from https://gitlab.com/jD91mZM2/xidlehook

# Only exported variables can be used within the timer's command
# export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

if command -v xidlehook
then
  # Run xidlehook
  # At 5 minute - suspend
  xidlehook \
    --not-when-fullscreen --not-when-audio \
    --timer 300 \
      '~/.config/i3/scripts/blur-lock && systemctl suspend' \
      ''
else 
  # Run xautolock if xidlehook not installed
  xautolock -time 5 -locker "systemctl suspend" -detectsleep
fi
